### ISSUE TITLE
vmfloaty_bolt backlog

### ISSUE THREAD

**Issue by gavindidrichsen** [gavindidrichsen-puppetlabs/vmfloaty_bolt#2]
```[tasklist]
### Tasks
- [ ] Add rspec tests
- [ ] Introduce bolt "reference" plugin, like the terraform one, except for vmfloaty
- [ ] Codify the selection, download, and verification of a pdk release artifact from jenkins build machine
```
