### ISSUE TITLE
Extract vmfloaty README examples into separate documents

### ISSUE THREAD

**Issue by gavindidrichsen** [gavindidrichsen-puppetlabs/vmfloaty_bolt#27]
```[tasklist]
### Tasks
- [ ] Create a separate `examples/peadm_setup` directory with it's own README
- [ ] Refactor the `peadm` example instructions into the new directory structure
- [ ] Consider using `markdown-notes-tree` to create a table of contents for the examples
```

**Comment by gavindidrichsen** [comment]
The following should be extracted into another document specifically for the purpose of showing how to setup the PEADM:

![Image](https://github.com/gavindidrichsen-puppetlabs/vmfloaty_bolt/assets/16652757/d352d6ee-fa25-4594-99e6-c4f22dd7992f)

Why is this important?  
* It simplifies the README to be just setup information

What are the conseqences?
* It creates a logical category for further examples
* The examples can be collected separately from the README and not clutter the top-level document.
